name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # - name: Setup Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker 
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        tags: franzfn/stock_app:latest
        # push: true
          # list all images, you will see my-ecr-repo/service and my-project/base
    - name: Look up images
      run: docker image ls

    # push the image manually, see above comment
    - name: Push image
      run: docker push franzfn/stock_app:latest
